
export const REQUEST_GROUP_LIST = "REQUEST_GROUP_LIST"
export const RESPONSE_GROUP_LIST = "RESPONSE_GROUP_LIST"

export const NAVIGATE_TO = "NAVIGATE_TO"
export const NAVIGATE_RESET = "NAVIGATE_RESET"

export const RESPONSE_SURVEY = "survey/RESPONSE_SURVEY"